spring:
  config:
    name: ai-agent-scaffold-app
    import:
      - classpath:agent/db-agent.yml
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1025MB
